# 基础镜像
FROM redis
# author
MAINTAINER xin

# 挂载目录
VOLUME /home/xin/redis
# 创建目录
RUN mkdir -p /home/xin/redis
# 指定路径
WORKDIR /home/xin/redis
# 复制conf文件到路径
COPY ./conf/redis.conf /home/xin/redis/redis.conf
