# 基础镜像
FROM  openjdk:8-jre
# author
MAINTAINER xin

# 挂载目录
VOLUME /home/xin
# 创建目录
RUN mkdir -p /home/xin
# 指定路径
WORKDIR /home/xin
# 复制jar文件到路径
COPY ./jar/xin-auth.jar /home/xin/xin-auth.jar
# 启动认证服务
ENTRYPOINT ["java","-jar","xin-auth.jar"]