# 基础镜像
FROM  openjdk:8-jre
# author
MAINTAINER xin

# 挂载目录
VOLUME /home/xin
# 创建目录
RUN mkdir -p /home/xin
# 指定路径
WORKDIR /home/xin
# 复制jar文件到路径
COPY ./jar/xin-modules-job.jar /home/xin/xin-modules-job.jar
# 启动定时任务服务
ENTRYPOINT ["java","-jar","xin-modules-job.jar"]